#!/usr/bin/env python3
"""Module for async generator comprehension.

This module provides a coroutine function that collects all random numbers
generated by an async generator into a list using async comprehension patterns.
"""
import typing
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> typing.List[float]:
    """Collect and return all numbers from async_generator.

    Uses an async for loop to iterate through all values generated by
    the async_generator coroutine and collects them into a list.

    Returns:
        List[float]: A list containing all random numbers generated
            by the async_generator function.
    """
    return [i async for i in async_generator()]
